FROM tensorflow/tensorflow:latest-py3
# При использовании оптимизированного Intel образа производительность деградирует более чем в 2 раза
# FROM docker.io/intelaipg/intel-optimized-tensorflow:2.0.0-mkl-py3

WORKDIR /StockMonitoring/

RUN pip3 install --upgrade pip && \
    pip3 install --upgrade setuptools pandas pydot graphviz tqdm


EXPOSE 1979/tcp

ENTRYPOINT /bin/bash -c "python3 ./predictor.py --train"