FROM tensorflow/tensorflow:latest-py3

RUN pip3 install --upgrade pip
RUN pip3 install --upgrade setuptools
RUN pip3 install --upgrade pandas pydot 
RUN pip3 install --upgrade graphviz tqdm matplotlib


EXPOSE 1979/tcp

ENTRYPOINT /bin/bash -c "python3 ./predictor.py --train"