FROM tensorflow/tensorflow:latest-gpu-py3

RUN apt-get -y update && apt-get install -y graphviz
RUN pip3 install --upgrade pip setuptools
RUN pip3 install --upgrade pandas pydot pydotplus
RUN pip3 install --upgrade graphviz tqdm matplotlib


EXPOSE 1979/tcp

ENTRYPOINT /bin/bash -c "python3 ./predictor.py --train"
